USE Foodster
GO


ALTER TABLE ORDR
ADD RID varchar(50)
ALTER TABLE ORDR
ADD FOREIGN KEY (RID) REFERENCES RESTAURANT(RID) 

--ALTER TABLE ORDR ADD CONSTRAINT fk_RID FOREIGN KEY (RID) REFERENCES RESTAURANT(RID);